name = "QuantumCircuitDraw"
uuid = "9bc3fc32-c1cb-4aa8-b380-0758771d981f"
authors = ["Nicolas Loizeau"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Documenter = "1.8.0"
Plots = "1.40.9"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
